// books-data.js — Reading lists and WGU coursework data
S.books={
  mission:[
    {title:"Man's Search for Meaning",author:'Viktor Frankl',done:false,tag:'core',notes:'',
     desc:"Frankl's account of surviving Nazi concentration camps and the psychological framework — logotherapy — that emerged from it. Central argument: meaning is the primary human drive, and it can be found even in unavoidable suffering. Direct foundation for the pecksmission.com thesis on suffering, purpose, and patient humanity."},
    {title:'Gesundheit! — Bringing Good Health to You, the Medical System, and Society',author:'Patch Adams',done:false,tag:'core',notes:'',
     desc:"Patch Adams makes the case that joy, humor, and human connection are not supplements to medicine — they are medicine. He built a free hospital on this premise. Read critically: where he was right, where idealism meets institutional reality, and what the medic-as-patient arc adds to his argument."},
    {title:'Being Mortal: Medicine and What Matters in the End',author:'Atul Gawande',done:false,tag:'core',notes:'',
     desc:"Gawande examines how modern medicine has failed dying patients by prioritizing prolonging life over quality of life. One of the clearest clinical arguments for treating the whole person. Directly supports the Osler gap argument and Phase 6–7 content on what the system misses at the end."},
    {title:'The Spirit Catches You and You Fall Down',author:'Anne Fadiman',done:false,tag:'core',notes:'',
     desc:"The story of a Hmong child with epilepsy and the collision between her family's beliefs and the American medical system. A masterclass in what happens when providers cannot hear the patient's full story. Foundational for the communication gap content in Phase 6."},
    {title:'When Breath Becomes Air',author:'Paul Kalanithi',done:false,tag:'core',notes:'',
     desc:"A neurosurgeon diagnosed with terminal cancer confronts what makes life meaningful when it is ending. The perspective flip — expert clinician becoming the patient — mirrors your own arc directly. One of the most important books on the list for understanding your story from the inside out."},
    {title:'The Doctor and the Soul',author:'Viktor Frankl',done:false,tag:'core',notes:'',
     desc:"Frankl's earlier and more clinical work, written before the camps. Argues that medicine must engage with the spiritual and existential dimensions of the patient — not just the biological. Companion to Man's Search for Meaning; goes deeper into the therapeutic framework."},
    {title:'How Doctors Think',author:'Jerome Groopman',done:false,tag:'clin',notes:'',
     desc:"Groopman investigates the cognitive errors physicians make — premature closure, anchoring, availability bias — and how those errors cost patients. Directly relevant to the disbelief gap in Phase 5. Shows the clinical mechanism behind why your symptoms were dismissed for 25 years."},
    {title:'The House of God',author:'Samuel Shem',done:false,tag:'clin',notes:'',
     desc:"A dark, satirical novel about medical internship that became a cult classic among physicians. Brutally honest about how training dehumanizes both patients and doctors. Read as a cultural document: this is the system your mission is pushing back against, and where it came from."},
    {title:"Complications: A Surgeon's Notes on an Imperfect Science",author:'Atul Gawande',done:false,tag:'clin',notes:'',
     desc:"Gawande's first major book — essays on the uncertainty, fallibility, and human cost of surgical medicine. Examines what happens when the system fails and how providers process that. Strong foundation for the Phase 3 and 7 content on systemic failure and documentation."},
    {title:'The Checklist Manifesto',author:'Atul Gawande',done:false,tag:'clin',notes:'',
     desc:"How a simple checklist dramatically reduced surgical deaths and errors. The argument: complexity kills, and systematic simplicity saves lives. Relevant to patient safety content (Phase 7) and the gap between what the system knows it should do and what it actually does."},
    {title:'On Death and Dying',author:'Elisabeth Kübler-Ross',done:false,tag:'clin',notes:'',
     desc:"The book that introduced the five stages of grief and transformed how medicine approaches dying patients. Essential foundation for the palliative care and grief counselor interviews (Phase 6) and for understanding what patients face that the clinical record never captures."},
    {title:'Mountains Beyond Mountains',author:'Tracy Kidder',done:false,tag:'rec',notes:'',
     desc:"The story of Paul Farmer, physician and anthropologist, who built a healthcare system in rural Haiti driven entirely by the belief that every person deserves the best care available. A model of what radical patient advocacy looks like in practice. Companion to the Patch Adams argument."},
    {title:'The Emperor of All Maladies',author:'Siddhartha Mukherjee',done:false,tag:'rec',notes:'',
     desc:"A biography of cancer — its history, science, politics, and the human cost of treatment. Pulitzer Prize winner. Relevant to the oncology nurse and chronic illness interviews, and to understanding how the system has both succeeded and failed cancer patients over a century."},
    {title:'Just Mercy',author:'Bryan Stevenson',done:false,tag:'rec',notes:'',
     desc:"Bryan Stevenson's account of fighting for the wrongly condemned in the American justice system. Not a healthcare book — but a masterclass in what it costs to advocate for people the system has decided are not worth fighting for. Direct structural parallel to veteran and patient advocacy."},
    {title:'Good to Great',author:'Jim Collins',done:false,tag:'rec',notes:'',
     desc:"Collins' research-based framework for what separates organizations that become truly great from those that remain merely good. Relevant to the WGU BSHA content on organizational leadership and to thinking about pecksmission.com as a platform that needs to be built to last."},
    {title:'Amusing Ourselves to Death',author:'Neil Postman',done:false,tag:'rec',notes:'',
     desc:"Postman's 1985 argument that television — and by extension all entertainment media — is reshaping public discourse and destroying the capacity for serious thought. Prescient for the social media age. Relevant to how patient advocacy content gets consumed and what depth of argument is still possible."},
    {title:'The Body Keeps the Score',author:'Bessel van der Kolk',done:false,tag:'vet',notes:'',
     desc:"Van der Kolk's landmark work on trauma — how it lives in the body, not just the mind, and why talk therapy alone is insufficient. Essential for the PTSD and MST interview content (Phase 4–5) and for understanding what combat veterans carry that the VA system consistently fails to address."},
    {title:'Tribe: On Homecoming and Belonging',author:'Sebastian Junger',done:false,tag:'vet',notes:'',
     desc:"Junger argues that the isolation of modern civilian life — not combat itself — is what breaks returning veterans. The tribe is the unit of belonging, and American society has lost the ability to provide it. Direct foundation for the Phase 4 veteran content and the military chaplain interviews."},
    {title:'Emotionally Healthy Spirituality',author:'Peter Scazzero',done:false,tag:'faith',notes:'',
     desc:"Scazzero's argument that emotional immaturity and spiritual depth cannot coexist — that genuine spiritual growth requires doing the interior emotional work most Christians avoid. Directly relevant to the faith layer woven through pecksmission.com and to your own story of recovery and meaning."},
    {title:'LifeWork',author:'Darrow L. Miller',done:false,tag:'faith',notes:'',
     desc:"Miller makes the biblical case for work as a calling, not a curse — that what we do Monday through Friday is as sacred as what happens on Sunday. Foundation for the GoBusiness200 content and for understanding the marketplace ministry framework your story operates inside."},
    {title:'Winning the Battle for the Minds of Men',author:'Dennis Peacocke',done:false,tag:'faith',notes:'',
     desc:"Peacocke's framework for cultural engagement from a Christian worldview — how to think strategically about influencing the systems and institutions that shape society. Directly relevant to the platform-building, patient advocacy, and Phase 7 system reform arguments."},
    {title:'On the Destiny of Nations: Resolving Our Economic Crisis',author:'Dennis Peacocke',done:false,tag:'faith',notes:'',
     desc:"Peacocke applies biblical economic principles to the crises facing modern nations. Dense and strategic. Read alongside GoBusiness200 and GoLife200 for the full framework on how faith, work, and cultural transformation connect."},
    {title:'The Road Back to You',author:'Ian Morgan Cron & Suzanne Stabile',done:false,tag:'faith',notes:'',
     desc:"An accessible introduction to the Enneagram — a personality framework rooted in ancient wisdom and increasingly used in Christian spiritual formation. Useful for understanding your own wiring, how you lead, and how you communicate — all of which shape how pecksmission.com is built and delivered."},
  ],
  wgu:[
    // ── TERM 1 ──
    {title:'Organizational Behavior',term:1,cu:3,area:'Business Management',
     desc:'Explores how to lead and manage effectively in diverse business environments. Apply organizational leadership theories and management strategies in scenario-based problems.',
     comp:['Analyze organizational culture to work effectively within it','Analyze leadership theories and select appropriate leader behavior','Describe influences on individual behavior','Determine team type and leadership for a given task','Develop and implement effective performance evaluation processes','Recommend principles for guiding group development'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Fundamentals for Success in Business',term:1,cu:3,area:'Business Core',
     desc:'Overview of the business field and how management, structure, communication, and leadership affect the business environment. Introduces power skills: time management, problem solving, emotional intelligence, ethics.',
     comp:['Communicate ideas and information in a professional setting','Identify common ethical issues within organizations','Identify leadership opportunities to enhance organizational performance','Recognize organizational functions and values','Recognize emotional reactions in professional situations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Emotional and Cultural Intelligence',term:1,cu:3,area:'Business Core',
     desc:'Key personal awareness skills in written, verbal, and nonverbal communication. Covers emotional intelligence (EI), cultural awareness, and ethical self-awareness.',
     comp:['Apply emotional intelligence to improve intrapersonal and interpersonal interactions','Demonstrate cultural intelligence within multicultural and business situations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Health, Fitness, and Wellness',term:1,cu:4,area:'General Education',
     desc:'Foundations of good health and physical fitness, addressing health, nutrition, fitness, and substance use and abuse.',
     comp:['Identify factors influencing mental, emotional, and social wellness','Identify core competencies of social and emotional learning','Identify influence of disease, fitness, and lifestyle on the body','Identify principles of nutrition and components of a healthy diet'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 2 ──
    {title:'Values-Based Leadership',term:2,cu:3,area:'Business Management',
     desc:'Learn by reflection, design, and scenario planning. Examines values-based leadership and creating a culture of care. Students identify personal values through assessment and map their influence on leadership.',
     comp:['Demonstrate how leadership abilities (listening, influence, ethical responsibility) solve problems','Describe how interpersonal skills enable effective collaboration and leadership','Explain how leadership of cultures fosters diversity, inclusion, ethics','Identify personal values (honesty, integrity, respect, EI, ethical responsibility)'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Principles of Management',term:2,cu:4,area:'Business Core',
     desc:'Introductory look at management in the business environment. Covers strategic planning, total quality, entrepreneurship, conflict and change, HR management, diversity, and organizational structure.',
     comp:['Apply principles of human resource management','Establish a total quality management program','Describe how to promote an entrepreneurial emphasis','Explain the strategic planning process','Recommend an organizational structure to match a given situation','Recommend techniques for managing conflict and change','Respond appropriately to diversity issues'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Healthcare Administration Evolution, Systems, and Leadership',term:2,cu:3,area:'Healthcare Administration',
     desc:'In-depth exploration of the U.S. healthcare system — its evolution, key stakeholders, business principles, leadership roles, health equity issues, and transformative influence of technology.',
     comp:['Describe the evolution of healthcare administration structure and function','Describe the role of leadership and management in healthcare administration','Explain the influence of business principles on healthcare operations and delivery','Identify opportunities and solutions in healthcare administration'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Composition: Writing with a Strategy',term:2,cu:3,area:'General Education',
     desc:'Three main topics: understanding purpose, context, and audience; writing strategies and techniques; editing and revising. Covers cross-cultural communication and common standards.',
     comp:['Compose constructive feedback of written texts','Construct a written document with correct format, style, structure, and grammar','Formulate a strategy for editing and revising written text','Incorporate writing strategies and techniques','Write with purpose for a given context and target audience'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 3 ──
    {title:'Healthcare Leadership and Community Engagement',term:3,cu:3,area:'Leadership and Management',
     desc:'Leadership principles in real-world contexts. Prepares students to analyze community needs and create change through community engagement and collaborative approaches.',
     comp:['Analyze impact of micro, mezzo, and macro sociopolitical drivers on community engagement','Develop a performance management strategy supporting professional identity of care providers','Develop strategic partnerships between community and organization','Propose interprofessional team strategies in complex community environments'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Critical Thinking: Reason and Evidence',term:3,cu:3,area:'General Education',
     desc:'Key critical thinking concepts applied to analysis and evaluation of reasons and evidence. Examines argument components, credibility of evidence, impact of bias, and constructing well-supported claims.',
     comp:['Evaluate bias and its impact','Evaluate evidence based on source credibility','Evaluate the quality of an argument','Make claims based on evidence'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Applied Healthcare Statistics',term:3,cu:4,area:'General Education',
     desc:'Foundational concepts in mathematics, introductory algebra, and statistics and probability applied to healthcare. Covers descriptive statistics, regression, correlation, and probability in clinical contexts.',
     comp:['Apply probability-based mathematics to explain and solve problems','Apply operations of basic algebra to evaluate quantitative expressions','Apply basic arithmetic operations','Apply fractions, decimals, and percentages','Evaluate categorical and quantitative data using graphical displays','Evaluate relationship between two quantitative variables through correlation and regression'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Business Accounting',term:3,cu:3,area:'Business Core',
     desc:'Introduction to the discipline of accounting. Fundamental knowledge of financial and managerial accounting, financial statements, budgeting, and managing costs and profits.',
     comp:['Explain how costs and profits are managed in business','Explain basic methods of budgeting','Explain the role of financial and managerial accounting','Explain the uses of financial statements'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Communication: Connecting with Others',term:3,cu:4,area:'General Education',
     desc:'Communication in the professional setting from multiple vantage points — communicating with others in varied contexts, across situations, and with diverse populations.',
     comp:['Implement appropriate communication styles based on audience and setting','Use communication strategies for managing conflict','Use communication strategies to influence others'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Professional Practice Experience I: Technical',term:3,cu:4,area:'Professional Practice',
     desc:'Uses EHRGo (electronic health record) to complete 42 structured activities experiencing how an HIM professional uses an EHR. Meets AHIMA Baccalaureate-level competencies. Earns 40 PPE hours.',
     comp:['Apply basic health informatics and information management skills','Display professionalism, reflection, and ethical behaviors as a health informatics professional','Evaluate operational components demonstrating adherence to regulatory standards and quality improvement'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Sociology',term:3,cu:4,area:'General Education',
     desc:'Learn to think like a sociologist — understand the hidden rules by which people live. Covers socializing institutions, organizations, governments, deviance, and social change.',
     comp:['Explain how societies are stratified across various social statuses','Explain major perspectives and key contributors to sociology','Explain reciprocal relationships between social institutions and individuals','Explain constructs of conformity and deviance from social norms','Identify components of culture and socialization'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Applied Algebra',term:3,cu:5,area:'General Education',
     desc:'Competence in working with functions and the algebra of functions. Covers linear, polynomial, exponential, and logistic functions with real-life healthcare applications.',
     comp:['Analyze graphical depictions of real-world situations using functional properties','Apply exponential functions to real-world problems','Apply linear functions to real-world problems','Apply logistic functions to real-world problems','Apply polynomial functions to real-world problems','Interpret real-world meaning of various functions','Verify the validity of a given model'],
     status:'not-started',notes:'Prerequisite: Applied Healthcare Statistics',tag:'wgu'},
    {title:'Human Growth and Development',term:3,cu:5,area:'General Education',
     desc:'Three-module course examining the entire human lifetime, from conception to death. Focuses on physical, cognitive, and psychosocial growth, cultural influences, emotions, and resilience.',
     comp:['Explain physical, cognitive, and psychosocial development conception through early childhood','Explain development from early adulthood to end of life','Explain development from middle childhood through adolescence','Explain influence of emotions and cultural perspectives from birth through early childhood','Explain influence of emotions from early adulthood to end of life','Explain influence of emotions from middle childhood through adolescence'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 4 ──
    {title:'Healthcare Policy and Governance',term:4,cu:4,area:'Healthcare Administration',
     desc:'Comprehensive exploration of healthcare policies, regulations, and governance and their impact on operations, administration, and community health services. Covers legal and ethical considerations.',
     comp:['Analyze impact of healthcare governance, policies, and regulations in various healthcare contexts','Explain the purpose of legal and regulatory frameworks in healthcare administration','Propose a healthcare administration solution that complies with policies and regulations'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 5 ──
    {title:'Fundamentals of Spreadsheets and Data Presentations',term:5,cu:3,area:'Business Core',
     desc:'Overview of spreadsheet functions and methods for presenting data. Features and uses of MS Excel applied to real-world situations. Introduction to collecting, organizing, and presenting data.',
     comp:['Create a presentation from a spreadsheet dataset','Perform common spreadsheet tasks requiring basic formatting, formulas, and functions','Prepare data for analysis'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Evidence-Based Healthcare Administration',term:5,cu:4,area:'Healthcare Administration',
     desc:'Apply evidence-based practices in healthcare administration. Data analytics, research methodologies, and evidence-based decision-making. Covers machine learning, AI, data collection, and statistical tools.',
     comp:['Apply data analytics to make decisions within healthcare administration','Explain how data supports decision-making in healthcare administration','Select applied research paradigms and methods in support of evidence-based practice (EBP)'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 6 ──
    {title:'Principles of Economics',term:6,cu:3,area:'Business Core',
     desc:'Foundational economic theories on markets and market behavior. Covers microeconomics (supply, demand, elasticity, market structure) and macroeconomics (monetary policy, fiscal policy, international trade).',
     comp:['Explain concepts in macroeconomics used in business and public policy','Explain concepts in microeconomics used in business and public policy','Explain fundamental economic principles'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Project Management',term:6,cu:3,area:'Business Management',
     desc:'Manage projects from start to finish. Covers project-management methods, project profiling and phases, constraints, building teams, scheduling, and risk management.',
     comp:['Apply elements of project planning to prepare key documents','Construct a project scheduling network diagram including critical path','Describe the project life cycle and how constraints impact a project','Explain how different types of project-management methods are used','Explain how project management helps organizations achieve goals','Explain key activities for executing, monitoring, controlling, and closing projects','Explain criteria and methods used for project selection'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Integrated Physical Sciences',term:6,cu:3,area:'General Education',
     desc:'Overview of the basic principles and unifying ideas of the physical sciences: physics, chemistry, and earth sciences. Focus on scientific reasoning and practical applications.',
     comp:['Describe the nature and process of science','Describe the underlying organization, interactions, and processes within the Earth system','Examine applications of key chemistry concepts including structure of matter','Examine applications of physics including forces, motion, energy, and waves'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Innovative and Strategic Thinking',term:6,cu:3,area:'Business Core',
     desc:'Knowledge and skills used in building and implementing business strategy. Covers management, innovative thinking, risk management, and strategic concepts. Quantitative literacy and data analysis for strategy.',
     comp:['Apply appropriate business practices to formulate recommendations impacting organizational effectiveness','Identify the impact of innovation in personal and professional settings','Utilize evidence-based techniques to make strategic decisions'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 7 ──
    {title:'Change Management',term:7,cu:3,area:'Business Management',
     desc:'Understanding change and successfully managing it using various methods and tools. Change theories and best practices, including approaches to recognizing, diagnosing, implementing, and sustaining change.',
     comp:['Describe different innovation strategies and the role leaders play in innovation','Explain how learning organizations develop and approach change','Explain how organizations diagnose the need for change and approaches for implementing it','Explain strategies, principles, roles, and models for sustaining change','Summarize theories related to change management'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Business Communication',term:7,cu:3,area:'Business Management',
     desc:'Survey of communication skills needed in the business environment. Writing messages, reports, and résumés; delivering oral presentations. Emphasizes communication processes, writing skills, and message types.',
     comp:['Apply business research and writing skills to present information','Apply effective communication techniques and principles to business environments','Apply principles of business writing to communicate','Compose multiple types of business messages','Create messages using technology and social media','Create professional communication documents for employment and advancement'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Business Finance',term:7,cu:3,area:'Business Core',
     desc:'The discipline of finance in the business environment. Financial ratios, time value of money concepts, and capital budgeting. Prerequisite: Introduction to Business Accounting.',
     comp:['Describe capital budgeting','Describe the systems, structure, roles, and impact of finance in business','Describe the uses of financial ratios to manage a business','Explain the application of time value of money concepts to business'],
     status:'not-started',notes:'Prerequisite: Introduction to Business Accounting',tag:'wgu'},
    {title:'Emergency Management and Planning in Healthcare',term:7,cu:4,area:'Healthcare Administration',
     desc:'Knowledge and skills to effectively manage emergencies in healthcare organizations. Covers crisis communication, ethical considerations, leadership in critical situations, public health, and community resilience.',
     comp:['Apply emergency management principles in various healthcare settings','Evaluate the impact of emergencies on healthcare organizations','Recommend strategies for creating and improving emergency response plans'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 8 ──
    {title:'Strategic Training and Development',term:8,cu:3,area:'Human Resources',
     desc:'Development of human capital by applying effective learning theories and practices for training and developing employees. Improving and empowering organizations through high-caliber training processes.',
     comp:['Analyze training and development needs and solutions to support organizational goals','Apply best practices for developing training programs and measuring their effectiveness','Describe the development and impact of talent management programs'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Operations and Supply Chain Management',term:8,cu:3,area:'Business Management',
     desc:'Introduction to efficiently producing goods and services, supply chain management strategies, and performance measurement. Covers forecasting, capacity planning, quality control, and inventory management.',
     comp:['Analyze factors involved in process design, capacity planning, and location analysis','Analyze forecasting models, measurement techniques, and scheduling methods','Analyze how just-in-time, TPS, and lean systems improve operating efficiency','Analyze the supply chain for competitive advantage','Explain appropriate quality management strategies','Explain how a business achieves goals through operations and inventory management'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Concepts in Marketing, Sales, and Customer Contact',term:8,cu:3,area:'Business Core',
     desc:'The discipline of marketing and its role in strategic and operational environments. Marketing planning, marketing mix, brand management, digital marketing, CRM, and personal selling.',
     comp:['Describe basic elements used in marketing planning','Describe how strategic marketing influences overall success of a business','Identify personal selling and negotiating strategies within the sales management process'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'American Politics and the US Constitution',term:8,cu:3,area:'General Education',
     desc:'Evolution of representative government and changing interpretations of civil rights and liberties protected by the Constitution. Covers powers of federal branches, federalism, and civic institutions.',
     comp:['Describe the influence of competing political ideologies on U.S. government development','Examine influence of political parties and NGOs on elections and political processes','Examine influence of media, public opinion, and political discourse on democracy','Examine the struggle to balance individual liberty, public order, and state\'s rights','Explain how structure and powers of U.S. government interact to form public policy'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 9 ──
    {title:'Exploring Emerging Trends in Healthcare Administration',term:9,cu:4,area:'Healthcare Administration',
     desc:'Impact of trends on healthcare administration, patient care, and industry transformation. Evaluates advancements transforming the healthcare industry. Integrates DEI principles, health disparities, and inclusive care.',
     comp:['Analyze emerging and evolving trends in healthcare','Create an implementation plan for emerging and evolving trends to advance organizational goals','Evaluate the impact of emerging and evolving trends in healthcare management and operations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Healthcare Administration Capstone',term:9,cu:4,area:'Healthcare Administration',
     desc:'Culminating experience of healthcare business administration. Integrates and synthesizes managerial skills with healthcare knowledge. Final project demonstrating professional managerial proficiency in a real-world scenario.',
     comp:['Exhibit artifacts demonstrating competency across all program areas and evidence of professional growth'],
     status:'not-started',notes:'Capstone project — apply learning to a real issue in your place of business',tag:'wgu'},
  ],
  faith:[
    {title:'GoLife100 · Sec 1: Life as Discovery',author:'GoLife100 · Dudley Hall',done:false,tag:'faith',notes:'',
     desc:'Taught by Dudley Hall. Covers the biblical foundations of a life well-lived — virtue, patience, love, and what it means to discover who you are in God before you try to do anything for Him. Foundational section for the entire GoLife framework.'},
    {title:'GoLife100 · Sec 2: Introduction to Worldview and Philosophy',author:'GoLife100 · Dr. Walter Duerr',done:false,tag:'faith',notes:'',
     desc:'Taught by Dr. Walter Duerr. Introduces the concepts of worldview, metaphysics, and ontology — the foundational questions of reality, truth, and ethics. Builds the intellectual framework for understanding why a Christian worldview produces a different approach to work, suffering, and culture than a secular one.'},
    {title:'GoLife100 · Sec 3: Root Presuppositions of the Christian Faith',author:'GoLife100 · Nature of God, Man, and Truth',done:false,tag:'faith',notes:'',
     desc:'Examines the foundational presuppositions of Christianity: the nature of God, the nature of man, and the nature of truth. Establishes why these presuppositions matter practically — not just theologically — and how they shape every decision a person of faith makes in the world.'},
    {title:'GoLife100 · Sec 4: Becoming a Prophetic Voice to Your Culture',author:'GoLife100 · Five Spheres of Government',done:false,tag:'faith',notes:'',
     desc:"Covers the five spheres of government (self, family, church, civil, marketplace) and what it means to be a Kingdom citizen with responsibility in each. The transition from personal faith to cultural engagement — how believers become prophetic voices rather than passive observers. Directly relevant to the pecksmission.com vision."},
    {title:'GoLife200 · Sec 1: Embracing God\'s Sovereignty',author:"GoLife200 · Destiny · God's Call",done:false,tag:'faith',notes:'',
     desc:"The advanced GoLife framework begins here with the question of calling and destiny. What does it mean to find your place on the wall — your specific, irreplaceable assignment? How do you discern God's call in the midst of hardship, recovery, and transition? Deeply relevant to what your surgery and mission represent."},
    {title:'GoLife200 · Sec 2: Embracing Community',author:'GoLife200 · Covenant · Generational Building',done:false,tag:'faith',notes:'',
     desc:'Covenant relationships, relational joining, and building something that outlasts you. Examines what genuine community requires — not just attendance or affinity, but covenant commitment. Relevant to the team-building and platform-building dimensions of the mission, and to the Stonebridge community context.'},
    {title:'GoLife200 · Sec 3: Strategic Lifestyle',author:'GoLife200 · Disciplines · Discerning Seasons',done:false,tag:'faith',notes:'',
     desc:'How to live strategically — aligning disciplines, rhythms, and decisions with your calling. Covers discerning seasons (what time is it?), the role of Sabbath, and building a life that is sustainable rather than driven. Directly relevant to the recovery, pacing, and long-term vision of the mission.'},
    {title:'GoLife200 · Sec 4: Problems as Opportunities',author:'GoLife200 · Becoming a Problem Solver',done:false,tag:'faith',notes:'',
     desc:"Reframes problems — in work, health, relationships, systems — as the raw material of Kingdom impact. The leader who solves the problem no one else wants to touch is the leader who earns influence. The patient advocacy argument in pecksmission.com is fundamentally a problem-solving argument."},
    {title:'GoLife200 · Sec 5: Engaging Culture',author:"GoLife200 · Hard Questions · God's Green Light",done:false,tag:'faith',notes:'',
     desc:"How to engage culture with conviction and wisdom — not defensively, not naively. What does it look like when God gives a green light into a hard space? How do you preserve spiritual growth while doing the messy, complicated work of cultural engagement? Closing section of the GoLife framework."},
    {title:'GoBusiness200 · Sec 1: Foundations of Marketplace Ministry',author:'GoBusiness200 · Biblical Economics · Kings and Priests',done:false,tag:'faith',notes:'',
     desc:'Establishes the theological and practical foundation for marketplace ministry — work as worship, business as a domain of Kingdom influence. Covers the kings-and-priests framework, biblical economics, and what financial freedom actually means from a Kingdom standpoint. Foundation for everything that follows.'},
    {title:'GoBusiness200 · Sec 2: Spiritual Foundations for Building',author:'GoBusiness200 · Hearing God for Business',done:false,tag:'faith',notes:'',
     desc:'How do you hear God for a business or a platform? What does it mean to discern trust — in partners, in direction, in timing? Covers the reality of spiritual warfare in organizational contexts and how to build in ways that survive it. Directly relevant to the pecksmission.com platform build.'},
    {title:'GoBusiness200 · Sec 3: Keys to Successful Business Life',author:'GoBusiness200 · Biblical Ethics · Organizational Calling',done:false,tag:'faith',notes:'',
     desc:"Covers the practical and ethical dimensions of building a successful business or organization from a Kingdom standpoint. What does your organization's calling look like? How do biblical ethics shape daily decisions? The transformation that the mission requires begins with your own transformation."},
    {title:'GoBusiness200 · Sec 4: Solving Problems God\'s Way',author:'GoBusiness200 · Execution · Delegation',done:false,tag:'faith',notes:'',
     desc:"Problem-solving in organizational context — how to discern the nature of a problem before trying to solve it, how to execute without burning out, and how to delegate in ways that develop people rather than just offload work. Practical leadership content with a Kingdom foundation."},
    {title:'GoBusiness200 · Sec 5: Managing and Mentoring People with Destiny',author:'GoBusiness200 · Relational Foundation · Teaching vs Training',done:false,tag:'faith',notes:'',
     desc:"The closing section of GoBusiness200 — how to lead people who have a destiny, not just a job description. The difference between teaching and training, between managing performance and developing a person. How do you know when the game is on? Directly relevant to leading your team and mentoring others through the mission."},
  ],
};
