// books-data.js — Reading lists and WGU coursework data
S.books={
  mission:[
    {title:"Man's Search for Meaning",author:'Viktor Frankl',done:false,tag:'core'},
    {title:'Gesundheit! — Bringing Good Health to You, the Medical System, and Society',author:'Patch Adams',done:false,tag:'core'},
    {title:'Being Mortal: Medicine and What Matters in the End',author:'Atul Gawande',done:false,tag:'core'},
    {title:'The Spirit Catches You and You Fall Down',author:'Anne Fadiman',done:false,tag:'core'},
    {title:'When Breath Becomes Air',author:'Paul Kalanithi',done:false,tag:'core'},
    {title:'The Doctor and the Soul',author:'Viktor Frankl',done:false,tag:'core'},
    {title:'How Doctors Think',author:'Jerome Groopman',done:false,tag:'clin'},
    {title:'The House of God',author:'Samuel Shem',done:false,tag:'clin'},
    {title:"Complications: A Surgeon's Notes on an Imperfect Science",author:'Atul Gawande',done:false,tag:'clin'},
    {title:'The Checklist Manifesto',author:'Atul Gawande',done:false,tag:'clin'},
    {title:'On Death and Dying',author:'Elisabeth Kübler-Ross',done:false,tag:'clin'},
    {title:'Mountains Beyond Mountains',author:'Tracy Kidder',done:false,tag:'rec'},
    {title:'The Emperor of All Maladies',author:'Siddhartha Mukherjee',done:false,tag:'rec'},
    {title:'Just Mercy',author:'Bryan Stevenson',done:false,tag:'rec'},
    {title:'Good to Great',author:'Jim Collins',done:false,tag:'rec'},
    {title:'Amusing Ourselves to Death',author:'Neil Postman',done:false,tag:'rec'},
    {title:'The Body Keeps the Score',author:'Bessel van der Kolk',done:false,tag:'vet'},
    {title:'Tribe: On Homecoming and Belonging',author:'Sebastian Junger',done:false,tag:'vet'},
    {title:'Emotionally Healthy Spirituality',author:'Peter Scazzero',done:false,tag:'faith'},
    {title:'LifeWork',author:'Darrow L. Miller',done:false,tag:'faith'},
    {title:'Winning the Battle for the Minds of Men',author:'Dennis Peacocke',done:false,tag:'faith'},
    {title:'On the Destiny of Nations: Resolving Our Economic Crisis',author:'Dennis Peacocke',done:false,tag:'faith'},
    {title:'The Road Back to You',author:'Ian Morgan Cron & Suzanne Stabile',done:false,tag:'faith'},
  ],
  wgu:[
    // ── TERM 1 ──
    {title:'Organizational Behavior',term:1,cu:3,area:'Business Management',
     desc:'Explores how to lead and manage effectively in diverse business environments. Apply organizational leadership theories and management strategies in scenario-based problems.',
     comp:['Analyze organizational culture to work effectively within it','Analyze leadership theories and select appropriate leader behavior','Describe influences on individual behavior','Determine team type and leadership for a given task','Develop and implement effective performance evaluation processes','Recommend principles for guiding group development'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Fundamentals for Success in Business',term:1,cu:3,area:'Business Core',
     desc:'Overview of the business field and how management, structure, communication, and leadership affect the business environment. Introduces power skills: time management, problem solving, emotional intelligence, ethics.',
     comp:['Communicate ideas and information in a professional setting','Identify common ethical issues within organizations','Identify leadership opportunities to enhance organizational performance','Recognize organizational functions and values','Recognize emotional reactions in professional situations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Emotional and Cultural Intelligence',term:1,cu:3,area:'Business Core',
     desc:'Key personal awareness skills in written, verbal, and nonverbal communication. Covers emotional intelligence (EI), cultural awareness, and ethical self-awareness.',
     comp:['Apply emotional intelligence to improve intrapersonal and interpersonal interactions','Demonstrate cultural intelligence within multicultural and business situations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Health, Fitness, and Wellness',term:1,cu:4,area:'General Education',
     desc:'Foundations of good health and physical fitness, addressing health, nutrition, fitness, and substance use and abuse.',
     comp:['Identify factors influencing mental, emotional, and social wellness','Identify core competencies of social and emotional learning','Identify influence of disease, fitness, and lifestyle on the body','Identify principles of nutrition and components of a healthy diet'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 2 ──
    {title:'Values-Based Leadership',term:2,cu:3,area:'Business Management',
     desc:'Learn by reflection, design, and scenario planning. Examines values-based leadership and creating a culture of care. Students identify personal values through assessment and map their influence on leadership.',
     comp:['Demonstrate how leadership abilities (listening, influence, ethical responsibility) solve problems','Describe how interpersonal skills enable effective collaboration and leadership','Explain how leadership of cultures fosters diversity, inclusion, ethics','Identify personal values (honesty, integrity, respect, EI, ethical responsibility)'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Principles of Management',term:2,cu:4,area:'Business Core',
     desc:'Introductory look at management in the business environment. Covers strategic planning, total quality, entrepreneurship, conflict and change, HR management, diversity, and organizational structure.',
     comp:['Apply principles of human resource management','Establish a total quality management program','Describe how to promote an entrepreneurial emphasis','Explain the strategic planning process','Recommend an organizational structure to match a given situation','Recommend techniques for managing conflict and change','Respond appropriately to diversity issues'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Healthcare Administration Evolution, Systems, and Leadership',term:2,cu:3,area:'Healthcare Administration',
     desc:'In-depth exploration of the U.S. healthcare system — its evolution, key stakeholders, business principles, leadership roles, health equity issues, and transformative influence of technology.',
     comp:['Describe the evolution of healthcare administration structure and function','Describe the role of leadership and management in healthcare administration','Explain the influence of business principles on healthcare operations and delivery','Identify opportunities and solutions in healthcare administration'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Composition: Writing with a Strategy',term:2,cu:3,area:'General Education',
     desc:'Three main topics: understanding purpose, context, and audience; writing strategies and techniques; editing and revising. Covers cross-cultural communication and common standards.',
     comp:['Compose constructive feedback of written texts','Construct a written document with correct format, style, structure, and grammar','Formulate a strategy for editing and revising written text','Incorporate writing strategies and techniques','Write with purpose for a given context and target audience'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 3 ──
    {title:'Healthcare Leadership and Community Engagement',term:3,cu:3,area:'Leadership and Management',
     desc:'Leadership principles in real-world contexts. Prepares students to analyze community needs and create change through community engagement and collaborative approaches.',
     comp:['Analyze impact of micro, mezzo, and macro sociopolitical drivers on community engagement','Develop a performance management strategy supporting professional identity of care providers','Develop strategic partnerships between community and organization','Propose interprofessional team strategies in complex community environments'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Critical Thinking: Reason and Evidence',term:3,cu:3,area:'General Education',
     desc:'Key critical thinking concepts applied to analysis and evaluation of reasons and evidence. Examines argument components, credibility of evidence, impact of bias, and constructing well-supported claims.',
     comp:['Evaluate bias and its impact','Evaluate evidence based on source credibility','Evaluate the quality of an argument','Make claims based on evidence'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Applied Healthcare Statistics',term:3,cu:4,area:'General Education',
     desc:'Foundational concepts in mathematics, introductory algebra, and statistics and probability applied to healthcare. Covers descriptive statistics, regression, correlation, and probability in clinical contexts.',
     comp:['Apply probability-based mathematics to explain and solve problems','Apply operations of basic algebra to evaluate quantitative expressions','Apply basic arithmetic operations','Apply fractions, decimals, and percentages','Evaluate categorical and quantitative data using graphical displays','Evaluate relationship between two quantitative variables through correlation and regression'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Business Accounting',term:3,cu:3,area:'Business Core',
     desc:'Introduction to the discipline of accounting. Fundamental knowledge of financial and managerial accounting, financial statements, budgeting, and managing costs and profits.',
     comp:['Explain how costs and profits are managed in business','Explain basic methods of budgeting','Explain the role of financial and managerial accounting','Explain the uses of financial statements'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Communication: Connecting with Others',term:3,cu:4,area:'General Education',
     desc:'Communication in the professional setting from multiple vantage points — communicating with others in varied contexts, across situations, and with diverse populations.',
     comp:['Implement appropriate communication styles based on audience and setting','Use communication strategies for managing conflict','Use communication strategies to influence others'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Professional Practice Experience I: Technical',term:3,cu:4,area:'Professional Practice',
     desc:'Uses EHRGo (electronic health record) to complete 42 structured activities experiencing how an HIM professional uses an EHR. Meets AHIMA Baccalaureate-level competencies. Earns 40 PPE hours.',
     comp:['Apply basic health informatics and information management skills','Display professionalism, reflection, and ethical behaviors as a health informatics professional','Evaluate operational components demonstrating adherence to regulatory standards and quality improvement'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Sociology',term:3,cu:4,area:'General Education',
     desc:'Learn to think like a sociologist — understand the hidden rules by which people live. Covers socializing institutions, organizations, governments, deviance, and social change.',
     comp:['Explain how societies are stratified across various social statuses','Explain major perspectives and key contributors to sociology','Explain reciprocal relationships between social institutions and individuals','Explain constructs of conformity and deviance from social norms','Identify components of culture and socialization'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Applied Algebra',term:3,cu:5,area:'General Education',
     desc:'Competence in working with functions and the algebra of functions. Covers linear, polynomial, exponential, and logistic functions with real-life healthcare applications.',
     comp:['Analyze graphical depictions of real-world situations using functional properties','Apply exponential functions to real-world problems','Apply linear functions to real-world problems','Apply logistic functions to real-world problems','Apply polynomial functions to real-world problems','Interpret real-world meaning of various functions','Verify the validity of a given model'],
     status:'not-started',notes:'Prerequisite: Applied Healthcare Statistics',tag:'wgu'},
    {title:'Human Growth and Development',term:3,cu:5,area:'General Education',
     desc:'Three-module course examining the entire human lifetime, from conception to death. Focuses on physical, cognitive, and psychosocial growth, cultural influences, emotions, and resilience.',
     comp:['Explain physical, cognitive, and psychosocial development conception through early childhood','Explain development from early adulthood to end of life','Explain development from middle childhood through adolescence','Explain influence of emotions and cultural perspectives from birth through early childhood','Explain influence of emotions from early adulthood to end of life','Explain influence of emotions from middle childhood through adolescence'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 4 ──
    {title:'Healthcare Policy and Governance',term:4,cu:4,area:'Healthcare Administration',
     desc:'Comprehensive exploration of healthcare policies, regulations, and governance and their impact on operations, administration, and community health services. Covers legal and ethical considerations.',
     comp:['Analyze impact of healthcare governance, policies, and regulations in various healthcare contexts','Explain the purpose of legal and regulatory frameworks in healthcare administration','Propose a healthcare administration solution that complies with policies and regulations'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 5 ──
    {title:'Fundamentals of Spreadsheets and Data Presentations',term:5,cu:3,area:'Business Core',
     desc:'Overview of spreadsheet functions and methods for presenting data. Features and uses of MS Excel applied to real-world situations. Introduction to collecting, organizing, and presenting data.',
     comp:['Create a presentation from a spreadsheet dataset','Perform common spreadsheet tasks requiring basic formatting, formulas, and functions','Prepare data for analysis'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Evidence-Based Healthcare Administration',term:5,cu:4,area:'Healthcare Administration',
     desc:'Apply evidence-based practices in healthcare administration. Data analytics, research methodologies, and evidence-based decision-making. Covers machine learning, AI, data collection, and statistical tools.',
     comp:['Apply data analytics to make decisions within healthcare administration','Explain how data supports decision-making in healthcare administration','Select applied research paradigms and methods in support of evidence-based practice (EBP)'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 6 ──
    {title:'Principles of Economics',term:6,cu:3,area:'Business Core',
     desc:'Foundational economic theories on markets and market behavior. Covers microeconomics (supply, demand, elasticity, market structure) and macroeconomics (monetary policy, fiscal policy, international trade).',
     comp:['Explain concepts in macroeconomics used in business and public policy','Explain concepts in microeconomics used in business and public policy','Explain fundamental economic principles'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Project Management',term:6,cu:3,area:'Business Management',
     desc:'Manage projects from start to finish. Covers project-management methods, project profiling and phases, constraints, building teams, scheduling, and risk management.',
     comp:['Apply elements of project planning to prepare key documents','Construct a project scheduling network diagram including critical path','Describe the project life cycle and how constraints impact a project','Explain how different types of project-management methods are used','Explain how project management helps organizations achieve goals','Explain key activities for executing, monitoring, controlling, and closing projects','Explain criteria and methods used for project selection'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Integrated Physical Sciences',term:6,cu:3,area:'General Education',
     desc:'Overview of the basic principles and unifying ideas of the physical sciences: physics, chemistry, and earth sciences. Focus on scientific reasoning and practical applications.',
     comp:['Describe the nature and process of science','Describe the underlying organization, interactions, and processes within the Earth system','Examine applications of key chemistry concepts including structure of matter','Examine applications of physics including forces, motion, energy, and waves'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Innovative and Strategic Thinking',term:6,cu:3,area:'Business Core',
     desc:'Knowledge and skills used in building and implementing business strategy. Covers management, innovative thinking, risk management, and strategic concepts. Quantitative literacy and data analysis for strategy.',
     comp:['Apply appropriate business practices to formulate recommendations impacting organizational effectiveness','Identify the impact of innovation in personal and professional settings','Utilize evidence-based techniques to make strategic decisions'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 7 ──
    {title:'Change Management',term:7,cu:3,area:'Business Management',
     desc:'Understanding change and successfully managing it using various methods and tools. Change theories and best practices, including approaches to recognizing, diagnosing, implementing, and sustaining change.',
     comp:['Describe different innovation strategies and the role leaders play in innovation','Explain how learning organizations develop and approach change','Explain how organizations diagnose the need for change and approaches for implementing it','Explain strategies, principles, roles, and models for sustaining change','Summarize theories related to change management'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Business Communication',term:7,cu:3,area:'Business Management',
     desc:'Survey of communication skills needed in the business environment. Writing messages, reports, and résumés; delivering oral presentations. Emphasizes communication processes, writing skills, and message types.',
     comp:['Apply business research and writing skills to present information','Apply effective communication techniques and principles to business environments','Apply principles of business writing to communicate','Compose multiple types of business messages','Create messages using technology and social media','Create professional communication documents for employment and advancement'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Introduction to Business Finance',term:7,cu:3,area:'Business Core',
     desc:'The discipline of finance in the business environment. Financial ratios, time value of money concepts, and capital budgeting. Prerequisite: Introduction to Business Accounting.',
     comp:['Describe capital budgeting','Describe the systems, structure, roles, and impact of finance in business','Describe the uses of financial ratios to manage a business','Explain the application of time value of money concepts to business'],
     status:'not-started',notes:'Prerequisite: Introduction to Business Accounting',tag:'wgu'},
    {title:'Emergency Management and Planning in Healthcare',term:7,cu:4,area:'Healthcare Administration',
     desc:'Knowledge and skills to effectively manage emergencies in healthcare organizations. Covers crisis communication, ethical considerations, leadership in critical situations, public health, and community resilience.',
     comp:['Apply emergency management principles in various healthcare settings','Evaluate the impact of emergencies on healthcare organizations','Recommend strategies for creating and improving emergency response plans'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 8 ──
    {title:'Strategic Training and Development',term:8,cu:3,area:'Human Resources',
     desc:'Development of human capital by applying effective learning theories and practices for training and developing employees. Improving and empowering organizations through high-caliber training processes.',
     comp:['Analyze training and development needs and solutions to support organizational goals','Apply best practices for developing training programs and measuring their effectiveness','Describe the development and impact of talent management programs'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Operations and Supply Chain Management',term:8,cu:3,area:'Business Management',
     desc:'Introduction to efficiently producing goods and services, supply chain management strategies, and performance measurement. Covers forecasting, capacity planning, quality control, and inventory management.',
     comp:['Analyze factors involved in process design, capacity planning, and location analysis','Analyze forecasting models, measurement techniques, and scheduling methods','Analyze how just-in-time, TPS, and lean systems improve operating efficiency','Analyze the supply chain for competitive advantage','Explain appropriate quality management strategies','Explain how a business achieves goals through operations and inventory management'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Concepts in Marketing, Sales, and Customer Contact',term:8,cu:3,area:'Business Core',
     desc:'The discipline of marketing and its role in strategic and operational environments. Marketing planning, marketing mix, brand management, digital marketing, CRM, and personal selling.',
     comp:['Describe basic elements used in marketing planning','Describe how strategic marketing influences overall success of a business','Identify personal selling and negotiating strategies within the sales management process'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'American Politics and the US Constitution',term:8,cu:3,area:'General Education',
     desc:'Evolution of representative government and changing interpretations of civil rights and liberties protected by the Constitution. Covers powers of federal branches, federalism, and civic institutions.',
     comp:['Describe the influence of competing political ideologies on U.S. government development','Examine influence of political parties and NGOs on elections and political processes','Examine influence of media, public opinion, and political discourse on democracy','Examine the struggle to balance individual liberty, public order, and state\'s rights','Explain how structure and powers of U.S. government interact to form public policy'],
     status:'not-started',notes:'',tag:'wgu'},
    // ── TERM 9 ──
    {title:'Exploring Emerging Trends in Healthcare Administration',term:9,cu:4,area:'Healthcare Administration',
     desc:'Impact of trends on healthcare administration, patient care, and industry transformation. Evaluates advancements transforming the healthcare industry. Integrates DEI principles, health disparities, and inclusive care.',
     comp:['Analyze emerging and evolving trends in healthcare','Create an implementation plan for emerging and evolving trends to advance organizational goals','Evaluate the impact of emerging and evolving trends in healthcare management and operations'],
     status:'not-started',notes:'',tag:'wgu'},
    {title:'Healthcare Administration Capstone',term:9,cu:4,area:'Healthcare Administration',
     desc:'Culminating experience of healthcare business administration. Integrates and synthesizes managerial skills with healthcare knowledge. Final project demonstrating professional managerial proficiency in a real-world scenario.',
     comp:['Exhibit artifacts demonstrating competency across all program areas and evidence of professional growth'],
     status:'not-started',notes:'Capstone project — apply learning to a real issue in your place of business',tag:'wgu'},
  ],
  faith:[
    {title:'GoLife100 · Sec 1: Life as Discovery',author:'GoLife100 · Dudley Hall · biblical foundations, virtue, patience, love',done:false,tag:'faith'},
    {title:'GoLife100 · Sec 2: Introduction to Worldview and Philosophy',author:'GoLife100 · Dr. Walter Duerr · metaphysics, ontology, ethics',done:false,tag:'faith'},
    {title:'GoLife100 · Sec 3: Root Presuppositions of the Christian Faith',author:'GoLife100 · Nature of God, Man, and Truth',done:false,tag:'faith'},
    {title:'GoLife100 · Sec 4: Becoming a Prophetic Voice to Your Culture',author:'GoLife100 · Five spheres of government · Kingdom citizenship',done:false,tag:'faith'},
    {title:'GoLife200 · Sec 1: Embracing God\'s Sovereignty',author:"GoLife200 · Finding your place on the wall · destiny · God's call",done:false,tag:'faith'},
    {title:'GoLife200 · Sec 2: Embracing Community',author:'GoLife200 · Covenant · relational joining · building generationally',done:false,tag:'faith'},
    {title:'GoLife200 · Sec 3: Strategic Lifestyle',author:'GoLife200 · Strategic thinking · disciplines · discerning seasons · Sabbath',done:false,tag:'faith'},
    {title:'GoLife200 · Sec 4: Problems as Opportunities',author:'GoLife200 · Becoming problem solvers · discerning the nature of a problem',done:false,tag:'faith'},
    {title:'GoLife200 · Sec 5: Engaging Culture',author:"GoLife200 · Hard questions · God's green light · preserving spiritual growth",done:false,tag:'faith'},
    {title:'GoBusiness200 · Sec 1: Foundations of Marketplace Ministry',author:'GoBusiness200 · Biblical economics · kings and priests · financial freedom',done:false,tag:'faith'},
    {title:'GoBusiness200 · Sec 2: Spiritual Foundations for Building',author:'GoBusiness200 · Hearing God for business · discerning trust · spiritual warfare in orgs',done:false,tag:'faith'},
    {title:'GoBusiness200 · Sec 3: Keys to Successful Business Life',author:'GoBusiness200 · Biblical ethics · organizational calling · transformation begins with you',done:false,tag:'faith'},
    {title:'GoBusiness200 · Sec 4: Solving Problems God\'s Way',author:'GoBusiness200 · Problem solving · execution + delegation · stimulating commitment',done:false,tag:'faith'},
    {title:'GoBusiness200 · Sec 5: Managing and Mentoring People with Destiny',author:'GoBusiness200 · Relational foundation · teaching vs training · knowing when the game is on',done:false,tag:'faith'},
  ],
};
