// calendar-data.js — 64-post content calendar
const CAL=[
  {ph:'Phase 1 · The Personal Record',posts:[
    {n:'01',t:'ch',ti:"Stand In Front of Me",gu:'Chart+Story · Surgery Day · Neuro assessments, pain documentation',st:'drafting'},
    {n:'02',t:'ch',ti:"Manage the Pain First",gu:'Chart+Story · Surgery Day · MRI order, pain scores, medication log',st:'planned'},
    {n:'03',t:'co',ti:"From the Other Side of the Table",gu:'Brain Surgery Survivor',st:'planned'},
    {n:'04',t:'ch',ti:"The Results My Family Was Waiting On",gu:'Chart+Story · Surgery Day · Lab orders, CBC, metabolic panel',st:'planned'},
    {n:'05',t:'ch',ti:"What Nobody Warned Me About Recovery",gu:"Chart+Story · Surgery Day · OT/PT notes, vital signs",st:'planned'},
    {n:'06',t:'in',ti:"The Medical Lab Scientist — The Person You'll Never Meet",gu:'Medical Lab Scientist · Barnes Jewish, St. Louis',st:'planned'},
    {n:'07',t:'ch',ti:"Continuity Isn't a Protocol — It's a Person",gu:'Chart+Story · Surgery Day · Shift change notes, nursing assignments',st:'planned'},
    {n:'08',t:'sl',ti:"The Thorn I Got to Have Removed",gu:'Solo · 2 Corinthians 12:9 expansion · theological center of the site',st:'planned'},
  ]},
  {ph:'Phase 2 · The Human Side of Care',posts:[
    {n:'09',t:'co',ti:"The Miracle and the Work",gu:'Car Accident Survivor · Roy Benavidez companion post',st:'planned'},
    {n:'10',t:'sl',ti:"What You're Wearing Tells Me Everything",gu:'Solo · Provider appearance / dress code · appearance is communication',st:'planned'},
    {n:'11',t:'sl',ti:"The Way You Talk to Me Matters More Than What You Say",gu:"Solo · Provider voice + tone · Dad's 7/38/55 framework",st:'planned'},
    {n:'12',t:'in',ti:"The CVICU Nurse — What We See That You Don't",gu:'CVICU Nurse · shared floor, two vantage points',st:'planned'},
    {n:'13',t:'ch',ti:"The Hiccup Trick and What It Taught Me",gu:'Chart+Story · Surgery Day · Nursing interventions log · two fingers below the neck',st:'planned'},
    {n:'14',t:'sl',ti:"What the Walker Taught Me That the Bench Never Could",gu:'Solo · Roy Benavidez · Fort Sam Houston · recovery as training',st:'planned'},
    {n:'15',t:'in',ti:"The Float Nurse — A Hospital Seen From Every Floor",gu:'Float Nurse · care culture variation across units',st:'planned'},
    {n:'16',t:'sl',ti:"The Gospel According to a Vision Test",gu:'Solo · Easter card moment · Surgery Day · faith without performance',st:'planned'},
    {n:'17',t:'in',ti:"The Ultrasound Tech — The Invisible Clinician",gu:'Ultrasound Technician · trained silence · what the note misses',st:'planned'},
    {n:'18',t:'sl',ti:"Patch Adams Was Right — And He Was Missing Something",gu:"Solo · Patch Adams + medic-to-patient arc · where he was right, what he missed",st:'planned'},
  ]},
  {ph:'Phase 3 · The System',posts:[
    {n:'19',t:'in',ti:"The Nurse Who Had Cancer — The Floor and the Bed",gu:'Nurse with Cancer · years giving care, then receiving it',st:'planned'},
    {n:'20',t:'sl',ti:"What the Chart Can't Capture",gu:"Solo · Chart synthesis · official vs full record · where patients get lost",st:'planned'},
    {n:'21',t:'in',ti:"The PA — What Makes a Good Doc",gu:"Physician's Assistant · inside the clinical system · Osler gap",st:'planned'},
    {n:'22',t:'sl',ti:"What Cerner Knows That Epic Doesn't — And Vice Versa",gu:'Solo · NP Cerner-to-Epic transition · documentation systems shape care',st:'planned'},
    {n:'23',t:'in',ti:"The Combat Medic Drill Sergeant — What We Built and What We Left Out",gu:'68W Combat Medic Drill Sergeant · origin post',st:'planned'},
    {n:'24',t:'sl',ti:"The Artillery Man's Diagnosis",gu:"Solo · Field artillery soldier companion · Doc vs Band-Aid argument",st:'planned'},
    {n:'25',t:'in',ti:"The VP of Operations — Where the System Breaks and Why",gu:'VP of Operations · Level 1 Trauma Hospital · operational diagnosis',st:'planned'},
  ]},
  {ph:'Phase 4 · The Stakes',posts:[
    {n:'26',t:'sl',ti:"What We Owe the People Who Signed the Blank Check",gu:'Solo · Veteran healthcare · bridge from system critique to veteran stakes',st:'planned'},
    {n:'27',t:'in',ti:"The VSO — What the VA Doesn't Tell You",gu:'Veteran Service Officer · VSA claim denials · patient advocacy',st:'planned'},
    {n:'28',t:'co',ti:"What Agent Orange Taught Me About What the System Really Is",gu:'Agent Orange Survivor · Vietnam veteran · extreme version of the argument',st:'planned'},
    {n:'29',t:'sl',ti:"The Mission Behind the Mission",gu:"Solo · pecksmission.com origin + faith · Patch Adams + Frankl + Benavidez + 2 Cor · closing statement",st:'planned'},
  ]},
  {ph:'Phase 5 · The Disbelief Gap',posts:[
    {n:'30',t:'sl',ti:"They Worked Next to Me and Still Didn't Believe It",gu:'Solo · Colleagues + diagnosis disbelief · disbelief as clinical failure',st:'planned'},
    {n:'31',t:'sl',ti:"What Misdiagnosis Actually Costs",gu:'Solo · Structural argument · physical, financial, psychological cost',st:'planned'},
    {n:'32',t:'in',ti:"Business Development, Vanderbilt — The Institutional View of the Gap",gu:'Leader of Business Development · Vanderbilt University Medical Center',st:'planned'},
    {n:'33',t:'sl',ti:"The Patient Who Knew Too Much",gu:'Solo · Clinical training as patient — double-edged sword',st:'planned'},
    {n:'34',t:'sl',ti:"25 Years Is Not a Fluke — It's a Pattern",gu:'Solo · Diagnostic delay · system built for clear presentations',st:'planned'},
    {n:'35',t:'in',ti:"Emergency Physician — The First Five Minutes",gu:'Emergency Physician · triage of humanity before triage of medicine',st:'planned'},
    {n:'36',t:'sl',ti:"You Don't Look Sick",gu:"Solo · Invisible illness · burden of proof falls on the patient",st:'planned'},
    {n:'37',t:'sl',ti:"The Difference Between a Symptom and a Story",gu:"Solo · Medicine's diagnostic language · what gets lost in translation",st:'planned'},
    {n:'38',t:'in',ti:"Neurologist — What the Imaging Misses",gu:'Neurologist · structural vs experiential · decade before the scan',st:'planned'},
    {n:'39',t:'sl',ti:"The Field Sobriety Test I Failed Stone Cold Sober",gu:'Solo · Military + neurological symptoms · failed test, blowing zeros · compressed brainstem',st:'planned'},
    {n:'40',t:'sl',ti:"What Osler Knew That We Keep Forgetting",gu:'Solo · Osler / system critique · 100+ years and still',st:'planned'},
    {n:'41',t:'in',ti:"Rare Disease Patient Advocate — When the System Has No Template",gu:'Rare Disease Patient Advocate · surviving a system not built for your condition',st:'planned'},
  ]},
  {ph:'Phase 6 · The Communication Gap',posts:[
    {n:'42',t:'sl',ti:"What Your Voice Does to Me Before Your Words Do Anything",gu:"Solo · 7/38/55 framework · Dad's model · Surgery Day moments · clinical case for vocal delivery",st:'planned'},
    {n:'43',t:'sl',ti:"What You're Wearing When You Walk in the Room",gu:'Solo · Provider appearance · Part Two version',st:'planned'},
    {n:'44',t:'in',ti:"Float Nurse — A Hospital Seen From Every Floor",gu:'Float Nurse · Part Two appearance',st:'planned'},
    {n:'45',t:'sl',ti:"Continuity Is a Person, Not a Protocol",gu:"Solo · Shift change · Matt's name on the board · what continuity actually means",st:'planned'},
    {n:'46',t:'sl',ti:"The Language of Medicine Was Never Written for Patients",gu:'Solo · Medical literacy · patient navigation · system designed for providers',st:'planned'},
    {n:'47',t:'in',ti:"Patient Experience Officer — What the Scores Don't Capture",gu:'Patient Experience Officer / Director · HCAHPS measures satisfaction, not humanity',st:'planned'},
    {n:'48',t:'sl',ti:"How to Advocate for Yourself When Nobody Is Listening",gu:'Solo · Practical patient advocacy · specific moves that work · caregivers share this',st:'planned'},
    {n:'49',t:'in',ti:"Hospital Chaplain — The Room Nobody Thinks to Enter",gu:'Hospital Chaplain · spiritual layer the system has no language for',st:'planned'},
    {n:'50',t:'sl',ti:"What Happens in the Break Room Ends Up at the Bedside",gu:'Solo · Care culture · culture is set between patients, not in the mission statement',st:'planned'},
    {n:'51',t:'sl',ti:"Pain Is Not a Number",gu:'Solo · 1–10 pain scale as documentation tool, not a clinical one · what it costs to translate lived pain',st:'planned'},
    {n:'52',t:'in',ti:"Nurse Who Became the Patient — The Floor and the Bed",gu:'Nurse with Personal Medical Crisis · Part Two version · what changed in practice',st:'planned'},
  ]},
  {ph:'Phase 7 · The System Gap',posts:[
    {n:'53',t:'sl',ti:"The Chart Is the Official Version. It Is Not the Full Version.",gu:'Solo · Chart synthesis · accurate vs complete · where patients get lost',st:'planned'},
    {n:'54',t:'sl',ti:"What the Documentation System Rewards — And What It Punishes",gu:'Solo · EHR incentive structures · tool changes workflow · workflow changes care',st:'planned'},
    {n:'55',t:'in',ti:"VP of Operations, Level 1 Trauma — Where the System Breaks and Why",gu:'VP of Operations · Level 1 Trauma · Part Two version',st:'planned'},
    {n:'56',t:'sl',ti:"What the Second Opinion Actually Costs",gu:'Solo · Patient trust · emotional and social cost of telling the system you don\'t trust it',st:'planned'},
    {n:'57',t:'sl',ti:"The Caregiver Nobody Asked About",gu:'Solo · Sapp + family in the waiting room · what caregivers go through that the system has no language for',st:'planned'},
    {n:'58',t:'in',ti:"PA — What Makes a Good Provider, From Inside the System",gu:"Physician's Assistant · Part Two version",st:'planned'},
    {n:'59',t:'sl',ti:"What We Owe the People Who Signed the Blank Check",gu:'Solo · Veteran healthcare · Part Two version · your combat medic background earns the right',st:'planned'},
    {n:'60',t:'sl',ti:"The Medic Who Became the Patient",gu:'Solo · Full identity arc · what transferred from training · what had to be unlearned · walker as starting line',st:'planned'},
    {n:'61',t:'in',ti:"VSO — What the VA Doesn't Tell You",gu:'Veteran Service Officer · Part Two version',st:'planned'},
    {n:'62',t:'sl',ti:"The Combat Medic Training Gap",gu:'Solo · 68W pipeline · civilian healthcare transition · what it costs when the training stops at the field',st:'planned'},
    {n:'63',t:'sl',ti:"What Comes After the Chart",gu:'Solo · Discharge + post-hospitalization · recovery is not a clinical event, it\'s a human one',st:'planned'},
    {n:'64',t:'in',ti:"Combat Medic Drill Sergeant — What We Built and What We Left Out",gu:'Combat Medic DS · Part Two version · final interview on the calendar',st:'planned'},
  ]},
];
